import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {Speedmeter} from '../components/speedmeter';
import {Costs} from '../components/costs'
import {Tips} from '../components/tips'
import { Tree } from '../components/tree';
import {config} from '../config';
import { Tip } from '../shared/types'

interface IProps {
  usage: any
  tips: Tip[]
}

const Home: NextPage = ({ usage, tips }: IProps) => {
  const {budget, usage:use} = usage;
  console.log(usage);
  console.log(tips)
  return (
    <div className={styles.container}>
      <Head>
        <title>The elders</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css" integrity="sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A=="
          crossOrigin="anonymous"
          referrerPolicy="no-referrer" 
        />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.mainHeader}>The Elders Got Your Back <i className="fa-solid fa-lightbulb"></i></h1>  
        <div className={styles.costsAndSpeedometerContainer}>
          <Costs />
          <Speedmeter maxValue={budget * 2} value={use}/>
        </div>  
        <div className={styles.tipsContainer}>
          <Tips tips={tips} />
          <Tree />
        </div>      
      </main>
    </div>
  )
}
const url = config.url;

export async function getStaticProps(){
  const usageRes = await fetch(url +'/api/usage');
  const tipsRes = await fetch(url + '/api/tips');
  const usage = await usageRes.json()
  const tips: Tip[] = await tipsRes.json()

  return {
    props:{
      usage,
      tips
    }
  }
}

export default Home
